# Generated by Django 3.1 on 2022-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='admin',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
